config/routes.rb
Rails.application.routes.draw do
  get "tasks",      to: "tasks#index",  as: :tasks
  get "task/:id",   to: "tasks#show",   as: :task
  get "tasks/new",  to: "tasks#new",    as: :new_task
  post "tasks", to: "tasks#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>
<div>
  <input id="task" type="checkbox" <%= "checked=''" if task.completed == true %>>
  <label for= task ><%= link_to task.title, task_path(task) %></label>
</div>
<% end %>

<br>

<%= link_to "+ new task", task_path(new_task) %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
 <%= f.label :title %>
 <br>
 <%= f.text_field :title %>
 <br>
 <br>
 <%= f.label :details %>
 <br>
 <%= f.text_field :details %>
 <br>
 <br>
 <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<%= link_to "< Back", tasks_path(tasks) %>